substitutions:
  moving_time: 35s
  name: Screen

esphome:
  name: screen
  friendly_name: Screens

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "a_key"

ota:
  - platform: esphome
    password: "abcdefg"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      hidden: false
      manual_ip: 
        static_ip: 1.2.3.4
        gateway: 1.2.3.4
        subnet: 255.255.255.0

captive_portal:

switch:
- platform: gpio
  pin: 1  #GPIO1 / connected to Somfy UP
  id: pin1
  restore_mode: ALWAYS_ON   # start HIGH
- platform: gpio
  pin: 2  #GPIO1 / connected to Somfy UP
  id: pin2
  restore_mode: ALWAYS_ON   # start HIGH
- platform: gpio
  pin: 3  #GPIO1 / connected to Somfy UP
  id: pin3
  restore_mode: ALWAYS_ON   # start HIGH

button:
  - platform: template
    name: Up
    id: s2_up
    icon: "mdi:menu-up"
    on_press:
      - logger.log: "Knop UP ingedrukt = output 3 even LOW = UP"
      - switch.turn_off: pin3   # negative: pin=off => output low
      - delay: 500ms 
      - switch.turn_on: pin3    # pin=on => output high
  - platform: template
    name: My
    id: s2_my
    icon: "mdi:gesture-tap-button"
    on_press:
      - logger.log: "Knop MY ingedrukt = output 2 even LOW = UP"
      - switch.turn_off: pin2   # negative: pin=off => output low
      - delay: 500ms 
      - switch.turn_on: pin2    # pin=on => output high
  - platform: template
    name: Down
    id: s2_down
    icon: "mdi:menu-down"
    on_press:
      - logger.log: "Knop DOWN ingedrukt = output 1 even LOW = UP"
      - switch.turn_off: pin1   # negative: pin=off => output low
      - delay: 500ms 
      - switch.turn_on: pin1    # pin=on => output high

cover:
  - platform: time_based
    name: Cover
    open_action:
      - button.press: s2_up
    open_duration: ${moving_time}
    close_duration: ${moving_time}
    close_action: 
      - button.press: s2_down
    stop_action: 
      - button.press: s2_my
    assumed_state: True
    has_built_in_endstop: True
